// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

var initialState_todos = [{
    title: "Initial todo",
    isDone: true
  }];

var initialState = {
  newTodoValue: "",
  todos: initialState_todos
};

function reducer(state, action) {
  if (typeof action === "number") {
    if (action !== 0) {
      return {
              newTodoValue: state.newTodoValue,
              todos: []
            };
    } else {
      return {
              newTodoValue: "",
              todos: state.todos.concat([{
                      title: state.newTodoValue,
                      isDone: false
                    }])
            };
    }
  } else {
    return {
            newTodoValue: action._0,
            todos: state.todos
          };
  }
}

function $$default(param) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  var handleClearTodos = function (param) {
    return Curry._1(dispatch, /* ClearTodos */1);
  };
  var handleChange = function ($$event) {
    var value = $$event.target.value;
    return Curry._1(dispatch, /* InputChanged */{
                _0: value
              });
  };
  var handleCreateTodo = function (param) {
    return Curry._1(dispatch, /* CreateTodo */0);
  };
  return React.createElement("div", {
              className: "p-6"
            }, React.createElement("input", {
                  className: "input input-bordered mr-5",
                  placeholder: "Type here",
                  value: state.newTodoValue,
                  onChange: handleChange
                }), React.createElement("button", {
                  className: "btn mr-3",
                  onClick: handleCreateTodo
                }, "Create"), React.createElement("button", {
                  className: "btn",
                  onClick: handleClearTodos
                }, "Clear"), React.createElement("ul", {
                  className: "mt-3 flex flex-col gap-4 bg-base-200 border-solid rounded"
                }, state.todos.map(function (todo) {
                      return React.createElement("li", {
                                  className: "p-3"
                                }, todo.title);
                    })));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
