// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$default(param) {
  return React.createElement("div", {
              className: "hero min-h-screen"
            }, React.createElement("div", {
                  className: "hero-content text-center"
                }, React.createElement("div", {
                      className: "max-w-md"
                    }, React.createElement("h1", {
                          className: "text-5xl font-bold"
                        }, "Next.JS + Rescript"), React.createElement("p", {
                          className: "py-6"
                        }, "ReScript is a robustly typed language that compiles to efficient and human-readable JavaScript. It comes with a lightning fast compiler toolchain that scales to any codebase size."), React.createElement("button", {
                          className: "btn btn-primary"
                        }, "Get started"))));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
